allowBuilds:
  esbuild: true
  unrs-resolver: true

peerDependencyRules:
  allowedVersions:
    'eslint-plugin-jsx-a11y>eslint': '10' # works fine on v10

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@entwico/*'
